sudo cp -r conf.d /etc/
sudo cp -r default /etc/
sudo cp -r modprobe.d /etc/
sudo cp -r modules-load.d /etc/
sudo cp -r NetworkManager /etc/
sudo cp -r pacman.d /etc/
sudo cp -r sensors.d /etc/
sudo cp -r sysctl.d /etc/
sudo cp -r systemd /etc/
sudo cp -r udev /etc/
sudo cp -r X11 /etc/
sudo cp -r chrony.conf /etc/
sudo cp -r dhcpcd.conf /etc/
sudo cp -r environment /etc/
sudo cp -r fancontrol /etc/
sudo cp -r fstab /etc/
sudo cp -r hosts /etc/
sudo cp -r makepkg.conf /etc/
sudo cp -r mkinitcpio.conf /etc/
sudo cp -r ntp.conf /etc/
sudo cp -r pacman.conf /etc/
sudo cp -r resolv.conf /etc/
sudo cp -r vconsole.conf /etc/
sudo cp -r zramswap.conf /etc/
