sudo cp -r /etc/conf.d ./
sudo cp -r /etc/default ./
sudo cp -r /etc/modprobe.d ./
sudo cp -r /etc/modules-load.d ./
sudo cp -r /etc/NetworkManager ./
sudo cp -r /etc/pacman.d ./
sudo cp -r /etc/sensors.d ./
sudo cp -r /etc/sysctl.d ./
sudo cp -r /etc/systemd ./
sudo cp -r /etc/udev ./
sudo cp -r /etc/X11 ./
sudo cp -r /etc/chrony.conf ./
sudo cp -r /etc/dhcpcd.conf ./
sudo cp -r /etc/environment ./
sudo cp -r /etc/fancontrol ./
sudo cp -r /etc/fstab ./
sudo cp -r /etc/hosts ./
sudo cp -r /etc/makepkg.conf ./
sudo cp -r /etc/mkinitcpio.conf ./
sudo cp -r /etc/ntp.conf ./
sudo cp -r /etc/pacman.conf ./
sudo cp -r /etc/resolv.conf ./
sudo cp -r /etc/vconsole.conf ./
sudo cp -r /etc/zramswap.conf ./
