sudo cp -r apm.service /usr/lib/systemd/system/
sudo cp -r fstrim.service /usr/lib/systemd/system/
sudo cp -r reflector.service /usr/lib/systemd/system/
sudo cp -r systemd-resolved.service /usr/lib/systemd/system/
sudo cp -r systemd-timesyncd.service /usr/lib/systemd/system/
sudo cp -r x86_energy_perf_policy.service /usr/lib/systemd/system/
sudo cp -r fstrim.timer /usr/lib/systemd/system/
sudo cp -r reflector.timer /usr/lib/systemd/system/
sudo cp -r systemd-timesyncd.timer /usr/lib/systemd/system/
